feat: [P4PU-672] removed transactions api
pagopa/arc-soak-test pull request #13
Opened 2024-11-07 08:27 UTC by oleksiybozhykntt

removed transactions api

2024-11-07 11:05 UTC, antonioT90 requested changes

2024-11-07 11:05 UTC, antonioT90 commented on .devops/soak-tests-pipeline.yml
> -      - getTransactions
let's add also 'runAll', 'runAllAuth', etc...

2024-11-07 17:00 UTC, oleksiybozhykntt commented on .devops/soak-tests-pipeline.yml
> -      - getTransactions
added

2024-11-07 17:06 UTC, antonioT90 requested changes

2024-11-07 17:06 UTC, antonioT90 commented on .devops/soak-tests-pipeline.yml
> +      - runAllTokenAssistance
if we rearrange this list in order to have:
* runAll as first
* runAll-<domain> before all domain related tests?

2024-11-07 17:06 UTC, antonioT90 commented on .devops/soak-tests-pipeline.yml
>      value: auth/getUserInfo
for each `runAll` you have to define here the folder to run

2024-11-07 17:06 UTC, antonioT90 commented on .devops/soak-tests-pipeline.yml
> +  - ${{ if eq(parameters.SCRIPT, 'runAll') }}:
this is not required!

2024-11-08 09:43 UTC, antonioT90 approved these changes

2024-11-08 09:55 UTC, merged